import type { NodeKind, Topology } from './sim/types';

/**
 * Sanitizes a node ID to be safe for Mermaid and Docker Compose identifiers.
 */
export function sanitizeIdentifier(id: string): string {
  const clean = id.replace(/[^a-zA-Z0-9_]/g, '_');
  return /^[a-zA-Z_]/.test(clean) ? clean : `node_${clean}`;
}

/**
 * Escapes labels for Mermaid strings.
 */
function escapeMermaidLabel(text: string): string {
  return text.replace(/"/g, "'");
}

/**
 * Generates Mermaid.js flowchart code from a Topology.
 */
export function exportToMermaid(topology: Topology): string {
  const lines: string[] = ['flowchart TD'];

  if (topology.nodes.length === 0) {
    return 'flowchart TD\n  empty["Empty Canvas"]';
  }

  // Define nodes with appropriate Mermaid shapes based on NodeKind
  for (const n of topology.nodes) {
    const id = sanitizeIdentifier(n.id);
    const label = escapeMermaidLabel(n.label);

    switch (n.kind) {
      case 'db':
      case 'timeseriesdb':
      case 'graphdb':
      case 'vectordb':
      case 'replica':
      case 'shard':
        lines.push(`  ${id}[("${label}")]`);
        break;
      case 'cache':
      case 'writebehind':
        lines.push(`  ${id}{{"${label}"}}`);
        break;
      case 'lb':
      case 'cdn':
      case 'apigateway':
      case 'edgecompute':
        lines.push(`  ${id}(["${label}"])`);
        break;
      case 'queue':
      case 'streambroker':
      case 'pubsub':
      case 'retryqueue':
        lines.push(`  ${id}[["${label}"]]`);
        break;
      case 'breaker':
      case 'ratelimiter':
      case 'bulkhead':
      case 'loadshedder':
        lines.push(`  ${id}{{"${label}"}}`);
        break;
      case 'client':
        lines.push(`  ${id}>"${label}"]`);
        break;
      default:
        lines.push(`  ${id}["${label}"]`);
        break;
    }
  }

  lines.push('');

  // Define edges
  for (const e of topology.edges) {
    const from = sanitizeIdentifier(e.from);
    const to = sanitizeIdentifier(e.to);

    if (e.control) {
      lines.push(`  ${from} -.->|controls| ${to}`);
    } else if (e.latencyMs && e.latencyMs > 0) {
      lines.push(`  ${from} -->|${e.latencyMs}ms| ${to}`);
    } else {
      lines.push(`  ${from} --> ${to}`);
    }
  }

  return lines.join('\n');
}

/**
 * Image and port configuration mapping for Docker Compose.
 */
interface ServiceTemplate {
  image: string;
  environment?: Record<string, string>;
  ports?: string[];
  command?: string;
}

function templateForKind(kind: NodeKind): ServiceTemplate {
  switch (kind) {
    case 'db':
    case 'replica':
    case 'shard':
      return {
        image: 'postgres:16-alpine',
        environment: {
          POSTGRES_DB: 'app',
          POSTGRES_USER: 'postgres',
          POSTGRES_PASSWORD: 'postgres_password',
        },
        ports: ['5432:5432'],
      };
    case 'cache':
    case 'writebehind':
      return {
        image: 'redis:7-alpine',
        ports: ['6379:6379'],
      };
    case 'queue':
    case 'pubsub':
    case 'retryqueue':
      return {
        image: 'rabbitmq:3-management-alpine',
        ports: ['5672:5672', '15672:15672'],
      };
    case 'streambroker':
      return {
        image: 'confluentinc/cp-kafka:7.5.0',
        environment: {
          KAFKA_NODE_ID: '1',
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT',
          KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092',
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1',
        },
        ports: ['9092:9092'],
      };
    case 'lb':
    case 'apigateway':
      return {
        image: 'nginx:alpine',
        ports: ['80:80'],
      };
    case 'searchindex':
      return {
        image: 'opensearchproject/opensearch:2.11.0',
        environment: {
          'discovery.type': 'single-node',
          'plugins.security.disabled': 'true',
        },
        ports: ['9200:9200'],
      };
    case 'worker':
      return {
        image: 'node:20-alpine',
        command: 'npm run worker',
      };
    default:
      return {
        image: 'node:20-alpine',
        command: 'npm start',
        ports: ['8080:8080'],
      };
  }
}

/**
 * Generates a valid docker-compose.yml string from a Topology.
 */
export function exportToDockerCompose(topology: Topology): string {
  const lines: string[] = [
    '# Generated by ScaleLab',
    '# https://github.com/scalelab',
    'version: "3.8"',
    '',
    'services:',
  ];

  // Map of dependencies (who calls whom)
  const outgoing = new Map<string, string[]>();
  for (const e of topology.edges) {
    if (e.control) continue;
    if (!outgoing.has(e.from)) outgoing.set(e.from, []);
    outgoing.get(e.from)!.push(sanitizeIdentifier(e.to));
  }

  // Filter out client and mock-only nodes
  const deployableNodes = topology.nodes.filter((n) => n.kind !== 'client' && n.kind !== 'region');

  if (deployableNodes.length === 0) {
    return 'version: "3.8"\nservices:\n  app:\n    image: node:20-alpine\n';
  }

  for (const node of deployableNodes) {
    const serviceName = sanitizeIdentifier(node.id);
    const tmpl = templateForKind(node.kind);
    const deps = outgoing.get(node.id)?.filter((d) => d !== serviceName) ?? [];

    lines.push(`  ${serviceName}:`);
    lines.push(`    image: ${tmpl.image}`);
    lines.push(`    container_name: scalelab_${serviceName}`);

    if (tmpl.command) {
      lines.push(`    command: ${tmpl.command}`);
    }

    if (tmpl.ports && tmpl.ports.length > 0) {
      lines.push('    ports:');
      for (const p of tmpl.ports) {
        lines.push(`      - "${p}"`);
      }
    }

    if (tmpl.environment && Object.keys(tmpl.environment).length > 0) {
      lines.push('    environment:');
      for (const [k, v] of Object.entries(tmpl.environment)) {
        lines.push(`      ${k}: "${v}"`);
      }
    }

    if (deps.length > 0) {
      lines.push('    depends_on:');
      for (const d of Array.from(new Set(deps))) {
        // Only depend on nodes that are also deployed
        if (deployableNodes.some((n) => sanitizeIdentifier(n.id) === d)) {
          lines.push(`      - ${d}`);
        }
      }
    }

    lines.push('    restart: unless-stopped');
    lines.push('');
  }

  return lines.join('\n');
}
